[package]
name = "terminal-habit-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features= ["widget-calendar"]}
color-eyre = "0.6.3"
crossterm = "0.28.1"
catppuccin = "2.5.1"
time = "0.3"
rusqlite = "0.37.0"

